### ISSUE TITLE
Failure when receiving data from the peer (CURLE_RECV_ERROR): OpenSSL SSL_read: Connection reset by peer, errno 104

### ISSUE THREAD

**Issue by barryvdh** [paynl/sdk#159]
Hello,

I'm sometimes receiving this error when receiving webhooks. Is this an hick-up in the API or something wrong on my side?

> Failure when receiving data from the peer (CURLE_RECV_ERROR): OpenSSL SSL_read: Connection reset by peer, errno 104

```
Paynl\Error\Error: Failure when receiving data from the peer (CURLE_RECV_ERROR): OpenSSL SSL_read: Connection reset by peer, errno 104 in /vendor/paynl/sdk/src/Api/Api.php:77
Stack trace:
#0 /vendor/paynl/sdk/src/Api/DirectDebit/DebitGet.php(44): Paynl\Api\Api->doRequest()
#1 /vendor/paynl/sdk/src/DirectDebit.php(91): Paynl\Api\DirectDebit\DebitGet->doRequest()
#2 /app/Libraries/DirectDebit/PayNLDirectDebit.php(98): Paynl\DirectDebit::get()
```

**Comment by barryvdh** [comment]
Today the same error occurred? Perhaps this occurs when too many requests are made?

**Comment by woutse** [comment]
Thanks for your message. Could you please sent this to support@pay.nl?

**Comment by SebLevDev** [comment]
We have the same issue today

```
# curl 'https://rest-api.pay.nl/v1/validate/isPayServerIp/json' -v 
*   Trying 37.46.137.138:443...
* Connected to [rest-api.pay.nl](http://rest-api.pay.nl/) (37.46.137.138) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=NL; ST=Zuid-Holland; O=Tintel BV; CN=*.[pay.nl](http://pay.nl/)
*  start date: Aug  8 00:00:00 2022 GMT
*  expire date: Aug 30 23:59:59 2023 GMT
*  subjectAltName: host "[rest-api.pay.nl](http://rest-api.pay.nl/)" matched cert's "*.[pay.nl](http://pay.nl/)"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
> POST /v1/validate/isPayServerIp/json HTTP/1.1
> Host: [rest-api.pay.nl](http://rest-api.pay.nl/)
> User-Agent: curl/7.74.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 30
>
* upload completely sent off: 30 out of 30 bytes
* TLSv1.2 (OUT), TLS alert, bad record mac (532):
* OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
* Closing connection 0curl: (56) OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
```

**Comment by escruickshank** [comment]
Thank you for your message. Could you please send this to support@pay.nl?
